apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: GOL
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/9880943813/GOL-Repo
    targetRevision: HEAD
  destination: 
    server: https://kubernetes.default.svc
    namespace: myappGOL

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
